package com.zowdow.direct_api.utils.constants;

public interface ExtraKeys {
    String EXTRA_ARTICLE_URL = "EXTRA_ARTICLE_URL";
    String EXTRA_ARTICLE_TITLE = "EXTRA_ARTICLE_TITLE";
    String EXTRA_RECYCLER_VIEW_STATE = "EXTRA_RECYCLER_VIEW_STATE";
    String EXTRA_RESTORED_SEARCH_KEYWORD = "EXTRA_RESTORED_SEARCH_KEYWORD";
    String EXTRA_RESTORED_CARD_FORMAT = "EXTRA_RESTORED_CARD_FORMAT";
    String EXTRA_API_INITIALIZED = "EXTRA_API_INITIALIZED";
}
